### ISSUE TITLE
Support test data in YAML files

### ISSUE THREAD

**Issue by txels** [txels/ddt#30]
Currently `ddt` supports feeding test data from a file, but that file has to be in JSON format.
Support for YAML seems like a good addition.

**Comment by txels** [comment]
Since YAML is not supported in Python's standard library, this would have to be an optional extension, since I do not want to force a YAML parser as a dependency for `ddt`. `ddt` should stay very lightweight and be very fast to install.

**Comment by pradyunsg** [comment]
BUMP!

I agree with not making it a "required" dependency and an optional one.

The JSON part can be used as it is currently used.
For YAML, if someone tries to use it, without PyYAML (or whichever library) installed, you can raise an error telling the user to install the same, otherwise it should just work as expected.

**Comment by txels** [comment]
Closed by #42
